# 配置端口
server:
  port: 8080
  domain: 47.96.131.208 #配合swagger使用 # 待部署域名
  version: jiumiaozho-lingfe-v1.0.0 # 当前代码版本
  wechat-api-url:
  wechat-js-api-debug: false
  wechat-js-api-beta: false
  asyncConfig: true
  asyncWeChatProgramTempList: true

spring:
  profiles:
    #  配置的环境
    active: yanglei
    #  数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #正式-https://adminjcx.gzsskj.cn/
    url: jdbc:mysql://47.96.131.208:3306/adminjcx_gzsskj?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: adminjcx_gzsskj
    password: 123456
  redis:
    #正式-https://adminjcx.gzsskj.cn/
    host: 47.96.131.208 #地址
    port: 6379 #端口
    password: lingfe-2021_OK #redispassword
    timeout: 1000 # 连接超时时间（毫秒）
    database: 0 #默认数据库
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1

debug: true
logging:
  level:
    io.swagger.*: error
    com.zbjk.crmeb: debug
    org.springframework.boot.autoconfigure: ERROR
  config: classpath:logback-spring.xml
  file:
    path: ./crmeb_log

# mybatis 配置
mybatis-plus:
  # 配置slq打印日志
  configuration:
    log-impl:

#swagger 配置
swagger:
  basic:
    enable: true #是否开启界面
    check: true #是否打开验证
    username: crmeb #访问swagger的账号
    password: 123456 #访问swagger的密码

#用于滑块验证-图片验证
afterImage:
  resourceHandler: /after/**
  location: D:/vc_image/
  #从当前路径的文件夹中读取，所有待选择文件
  imgsPath: D:\lingfe\git\validateCodeSlider\static\image\